spring.application.name=ms-rutaexpress-catalog
server.port=8082

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

spring.security.oauth2.resourceserver.jwt.issuer-uri=${AZURE_ISSUER_URI}
spring.security.oauth2.resourceserver.jwt.audiences=${AZURE_AUDIENCE}
